Makefile, deploy/olm-catalog/node-maintenance-operator/0.2.0/node-maintenance-operator.v0.2.0.clusterserviceversion.yaml, manifests/node-maintenance-operator/node-maintenance-operator.package.yaml, manifests/node-maintenance-operator/v0.2.0/node-maintenance-operator.v0.2.0.clusterserviceversion.yaml, manifests/node-maintenance-operator/v0.2.0/nodemaintenance_crd.yaml, olm-deploy-manifests/nm-catalog-source.yaml, olm-deploy-manifests/nm-sub.yaml
Increased node-maintenance-operator version to 0.2.0
/cc @yanirq
=> increased version

build/Dockerfile.registry, manifests/node-maintenance-operator/node-maintenance-operator.package.yaml, manifests/node-maintenance-operator/v0.4.0/node-maintenance-operator.v0.4.0.clusterserviceversion.yaml, manifests/node-maintenance-operator/v0.4.0/nodemaintenance_crd.yaml
same issue as fixed on https://github.com/kubevirt/cluster-network-addons-operator/pull/215 
+ added corresponding files for v0.4.0
=> Fix registry Dockerfile to work with origin-registry-operator 4.2.0

pkg/controller/nodemaintenance/nodemaintenance_controller_test.go, pkg/controller/nodemaintenance/taint.go
Fix removal of existing taints that are not related to the maintenance operation while putting node in and out of maintenance .
**Problem description** 
Starting maintenance on a node should add `node.kubernetes.io/unschedulable:NoSchedule` and `kubevirt.io/drain:NoSchedule` taints to it , but in doing so it removed all other taints that pre existed prior to maintenance.
The same happened when stopping maintenance on a node.
=> Fix unwanted taint removals

Gopkg.lock, pkg/controller/nodemaintenance/drain.go, pkg/controller/nodemaintenance/nodemaintenance_controller.go, pkg/controller/nodemaintenance/taint.go
Re-factor log messages in code to be coherent and use the same format.
Human readable timestamps will now be available on log messages.
=> Refactor Logging in controller logic

pkg/controller/nodemaintenance/nodemaintenance_controller.go
**Problem Description**
- If a maintenance CR with an invalid node name is created then it cannot be deleted since the reconciliation flow did not allow the removal of the CR's finalizer in that scenario. 
- In case a maintenance CR with an valid node name is created but then the node was removed from the cluster then it cannot be deleted as well.
**Solution**
Fix the reconciliation flow to remove the finalizer in case the node in the maintenance CR does not exist. 
Fixes #33
=> Remove finalizer when node does not exist

pkg/controller/nodemaintenance/drain.go
**Problem Description** 
For each reconciliation of the maintenance controller a go routine was created to call pod evictions.
The problem was that when a new reconciliation round has started these go routines kept running - trying to evict the same pod/s simultaneously 
**Solution**
Every time a reconciliation round ends (currently hard coded for 1 minute) 
The eviction go routine will be closed and a new one is opened. Meaning only one eviction routine for each reconciliation.
=> Close eviction routine on reconciliation

pkg/controller/nodemaintenance/drain.go
Stopping the eviction routine according to reconciliation was done in the wrong place.
The forced closure by channel should have occurred only in case of an error that would keep the eviction routine going.
=> Fix race of eviction closure routine

test/e2e/nodemaintenance_test.go
**What this PR does / why we need it:**
Show operator logs on errors in e2e test run.
**Special notes for your reviewer:**
**Release note:**
```
NONE
```
=> Improve diagnostics of e2e tests.

README.md, deploy/crds/nodemaintenance_cr.yaml, deploy/crds/nodemaintenance_crd.yaml, deploy/role.yaml, manifests/generated/node-maintenance-operator.vVERSION.clusterserviceversion.yaml, pkg/apis/kubevirt/v1alpha1/register.go, test/e2e/nodemaintenance_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1766522
/cc @yanirq, @tiraboschi, @beekhof 
Signed-off-by: Karel Simon <ksimon@redhat.com>
=> move node maintenance operator to its own api group

OWNERS
See thread  'Establishing a link between BZ components and OpenShift artifacts'
```release-note
NONE
```
=> Add bugzilla information to OWNERS

build/csv-generator.sh, build/make-csv-generator.sh, deploy/operator.yaml, manifests/node-maintenance-operator/v0.6.0/node-maintenance-operator.v0.6.0.clusterserviceversion.yaml
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1840220
WATCH_NAMESPACE doesn't get initialised properly
=> fix WATCH_NAMESPACE env variable in container spec of generated CSV

OWNERS
=> Added slintes to OWNERS

Makefile, README.md, deploy/deployment-k8s/catalogsource.yaml, deploy/deployment-k8s/namespace.yaml, deploy/deployment-k8s/operatorgroup.yaml, deploy/deployment-k8s/subscription.yaml, deploy/deployment-ocp/catalogsource.yaml, deploy/deployment-ocp/namespace.yaml, deploy/deployment-ocp/operatorgroup.yaml, deploy/deployment-ocp/subscription.yaml, hack/generate-bundle.sh, hack/sync.sh
=> Provide deployment manifests for the latest published images

deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml, deploy/olm-catalog/node-maintenance-operator/node-maintenance-operator.package.yaml, manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml, manifests/node-maintenance-operator/template/node-maintenance-operator.package.yaml, manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, manifests/node-maintenance-operator/v0.7.0/node-maintenance-operator.package.yaml
- int vs string in yaml issue
- valid provider name for Red Hat Operatorhub
=> Small fixes for manifests

.gitignore, Makefile, must-gather/Dockerfile, must-gather/README.md, must-gather/collection-scripts/gather, must-gather/collection-scripts/version
It will gather
- objects in the operator's namespace
- nodemaintenance CRs
- nodes
```release-note
Added must-gather image
```
=> Added must-gather image

must-gather/collection-scripts/gather
=> Added machines to must-gather, fixed default operator ns

OWNERS
=> Added Nir as reviewer and approver

cmd/manager/main.go
Webhook works now for cluster scoped CRD when being installed in ownNamespace mode.
```release-note
NONE
```
=> Remove webhook workaround, not needed anymore

.travis.yml, Makefile, build/Dockerfile, hack/build.sh, hack/release-manifests.sh
- Use correct build command with version info in Dockerfile and move commands into script
- Fixed preparation of release manifests
```release-note
NONE
```
=> Fix release

build/index.Dockerfile.ci.intermediate
=> Change CI hostname to match the recent hostname reported in CI logs

.dockerignore, Makefile, build/check.Dockerfile
Needed for moving the check job from Travis to KubeVirtCI
=> Dockerize "make check" command

README.md
Suprisingly useful PR which initially only was intended for testing postsubmit CI jobs for pushing images after merge ;)
Will merge immediatly.
=> Test PR for postsubmit jobs

OWNERS
=> add mshitrit as an approver and reviewer

deploy/crds/nodemaintenance.kubevirt.io_nodemaintenances_crd.yaml, deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml, deploy/olm-catalog/node-maintenance-operator/manifests/nodemaintenance.kubevirt.io_nodemaintenances_crd.yaml, deploy/webhooks/nodemaintenance.webhook.yaml, hack/generate-crds.sh, manifests/node-maintenance-operator/v0.9.0/manifests/node-maintenance-operator.clusterserviceversion.yaml, manifests/node-maintenance-operator/v0.9.0/manifests/nodemaintenance.kubevirt.io_nodemaintenances_crd.yaml, manifests/node-maintenance-operator/v9.9.9/manifests/node-maintenance-operator.clusterserviceversion.yaml, manifests/node-maintenance-operator/v9.9.9/manifests/nodemaintenance.kubevirt.io_nodemaintenances_crd.yaml
```release-note updating nmo version from v1beta1 to v1```
=> 3923 move nmo crd and webhook from v1beta1 due to api deprecation

bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml, config/default/kustomization.yaml, config/default/manager_ports_patch.yaml, config/manifests/kustomization.yaml
Causes trouble in HCO, and other components don't use it as well
```release-note
Remove proxy container
```
=> Remove auth-proxy container

Makefile, must-gather/Dockerfile, must-gather/README.md, must-gather/collection-scripts/gather, must-gather/collection-scripts/version
```release-note
Added initial version of must gather image
```
=> Add initial version of must-gather image

hack/csv-generator.sh
/release-note-none
/cherry-pick release-0.11
=> Fix names in CSV for HCO

bundle/manifests/node-maintenance-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/node-maintenance-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/node-maintenance-operator-webhook-service_v1_service.yaml, bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml, bundle/manifests/nodemaintenance.kubevirt.io_nodemaintenances.yaml, config/default/kustomization.yaml, config/manager/manager.yaml
OLM can't update deployments with modified labels...
=> Revert label changes
