README.md
deploy/crds/kubevirt_v1alpha1_nodemaintenance_crd.yaml
deploy/operator.yaml
pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
pkg/apis/kubevirt/v1alpha1/zz_generated.openapi.go
pkg/controller/nodemaintenance/nodemaintenance_controller.go
pkg/controller/nodemaintenance/taint.go
pkg/controller/nodemaintenance/utils.go
test/e2e/nodemaintenance_test.go

Changed scheme for NodeMaintenance CR to support the following structure:
apiVersion: kubevirt.io/v1alpha1
kind: NodeMaintenance
metadata:
name: nodemaintenance-xyz
spec:
nodeName: node02
reason: "Test node maintenance"
fixes #3

Add node name under Spec

---

pkg/controller/nodemaintenance/nodemaintenance_controller.go
pkg/controller/nodemaintenance/taint.go

**What this PR does / why we need it:**
This PR comes to deal with a race condition caused by node lifecycle controller which adds/removes a `node.kubernetes.io/unschedulable:NoSchedule` taint after we cordon/uncordon the node
and by that causes the `node.kubernetes.io/unschedulable:NoSchedule` not to be added/removed (sometimes - according to the race)  
For that reason, also the `node.kubernetes.io/unschedulable:NoSchedule` taint will be added/removed directly on/from the node to avoid collisions with the kubernetes node lifecycle controller

Add/Remove NodeUnschedulableTaint on maintanance creation/deletion.

---

README.md
deploy/crds/nodemaintenance_crd.yaml
pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
pkg/controller/nodemaintenance/nodemaintenance_controller.go
pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
pkg/controller/nodemaintenance/utils.go
test/e2e/nodemaintenance_test.go

Updated Node maitenance CR status to contain the following:
`pendingPods` PendingPods is a list of pending pods for eviction. - fixed to hold pods names (instead of pod objects) 
`totalPods` is the total number of all pods on the node from the start.
`evictionPods` is the total number of pods up for eviction from the start.

Add pod statistics to status

---

Makefile
build/Dockerfile
build/Dockerfile.registry
build/csv-generator.sh
build/make-csv-generator.sh
build/make-manifests.sh
manifests/generated/node-maintenance-operator.vVERSION.clusterserviceversion.yaml

This PR adds the HCO's csv-generator logic to the nmo's container image and follows the same pattern found [here](https://github.com/MarSik/kubevirt-ssp-operator/pull/66) for the ssp operator. 
New make csv-generator make target generates a reusable pre-generated CSV file with placeholder values in the manifests/generated dir.
make container-build-operator copies in both the placeholder CSV file and the new csv-generator script
The operator's container can now be used to generate a corresponding CSV file using the csv-generator entry-point.
**Basic Example**
```
docker run -it -rm --entrypoint=/usr/bin/csv-generator <operator image> --csv-version=1.1.1 --operator-image=someregistry/nmo-opereator:sometag --namespace=placeholder
```
The HCO will be using this csv-generator entrypoint in the …

Add csv-generator script to operator container image

---

Makefile
hack/coverage.sh
pkg/controller/nodemaintenance/nodemaintenance_controller.go
pkg/controller/nodemaintenance/nodemaintenance_controller_init.go

add generation of coverage report on unit tests to the build
- run ginkgo with coverage flags
- postedit resulting coverage report so that git tool cover can parse it
- exclude files that are not supposed to be covered by coverage report.
- display function coverage report (textual)
- generage html coverage report (this is only useful if run in
interactive mode, here the default browser is invoked and displays the
html coverage report)
The significant coverage number appears at the end of the function
report.

Add coverage report to build

---

deploy/crds/nodemaintenance_crd.yaml
hack/functest.sh
test/e2e/nodemaintenance_test.go

fix an error while validating the openapi schema. 
The last two commits of the PR are a check for openAPI validation errors in the e2e tests, and the fix of the CRD
This PR is created from #68 by cherry picking its changes of top of the new master branch.

fix openapi validation error for CRD of node maintenance operator

---

README.md
olm-deploy-manifests/nm-catalog-source.yaml
olm-deploy-manifests/nm-sub.yaml

Starting with OCP 4.2, the namespace for global catalogs has
been changed to openshift-marketplace.
Signed-off-by: Richard Su <rwsu@redhat.com>

Update catalog namespace for OCP 4.2 and higher

---

Makefile
hack/clean.sh

make cluster-clean stopped working after using new upstream ci.
wasn't noticed  as this is not used in build process.

make cluster-clean broken after using new ci 

---

pkg/controller/nodemaintenance/nodemaintenance_controller.go

nmo logs appear in reference time, change that to a human readable
format

improve log format of nmo

---

Makefile
hack/functest.sh
hack/sync.sh

Fixed usage of the "external" KubevirtCI provider:
- pass image registry and tag to sync script
- skip usage of cluster registry for external provider
- use existing KUBECONFIG var for functest
After this you can use an existing cluster (assuming a correctly configured KUBECONFIG) for deploying and running functests, e.g.
```
export KUBEVIRT_PROVIDER=external
export IMAGE_REGISTRY=quay.io/<user>
make container-build container-push cluster-up cluster-sync cluster-functest
```

Fix "external" CI provider

---

automation/test.sh

moved version in .travis.yml - but automation test use their own gimme
invocation. change automation test script to use the same version,

automation test: use the same go version as specified in .travis.yml

---

Makefile
hack/commit-msg-hook.sh
hack/precommit-hook.sh
hack/prepare-commit-msg-hook.sh
hack/whitespace.sh

- make check installs a pre-commit hook that reports whitespace issues (trailing whitespace or multiple empty lines). the pre-commit hook checks files that are about to be commited for whitespace problems.
- make whitespace-check now reports files with multiple empty lines as errors.
- make whitepace-commit : fixes whitespace issues in files added for commit with git add.
- while we are at here: also add git hook that sets the signoff message into the commit message, so that you don't have to do git commit --amend --signoff 
The rational for these changes is that it is more appropriate to fix trailing whitespaces and multiple empty lines when you are about to commit something

whitespace fixes as precommit hook

---

Makefile

last commit damaged the makefiles phony claus. now I fix it back again.

fix makefile: phony clause got broken

---

pkg/controller/nodemaintenance/nodemaintenance_controller.go
pkg/controller/nodemaintenance/nodemaintenance_controller_test.go

CR object must be deleted when node is being deleted. Therefore we need to add an owner ref from CR object to node.
The node ref is BlockOwnerDeletion = false, this requires us to do additional check when deleting the object. This creates the cleanup scenario:  referred to node has been deleted but lease hasn't. 
(or should we rather add a owner ref from lease object to the node?) Didn't see anyone setting the owner ref of node lease in any usage of leases).

set owner ref on nmo CR to the node object

---

Makefile
cmd/manager/main.go
deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
deploy/operatorgroup.yaml
deploy/webhooks/nodemaintenance.webhook.yaml
hack/sync.sh
manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
pkg/apis/nodemaintenance/v1beta1/nodemaintenance_api_suite_test.go
pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator.go
pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator_test.go
test/e2e/nodemaintenance_test.go

For validation of CRs during creation and updates we need a validation webhook.
Replaces #84 
Fixes #97 
Fixes #58 
Validations implemented in this PR are:
- on creation:
- validate nodename, a node with that name has to exist
- prevent multiple CRs for the same node
- on update:
- prevent nodename change
Interesting implementation details:
- Added `deploy/webhooks/nodemaintenancd.webhook.yaml`, will be added to CSVs by `make generate-bundle`
- Restrict `installMode` to `AllNamespaces` only, and modified `OperatorGroup` accordingly. Otherwise OLM will restrict webhook calls to CRs in namespaces of the OperatorGroup, which doesn't work for cluster scoped CRDs.
- Added code for serving the webhook
- Workaround for OLM installation: patch olm-operator to `latest` image because of unreleased …

Added validation webhook

---

README.md

Noted that after deploying the CatalogSource on Openshift, you can go on in the OperatorHub UI

Improved deployment instructions in README.md

---

Makefile
deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
deploy/role.yaml
deploy/webhooks/nodemaintenance.webhook.yaml
hack/functest.sh
hack/get-opm.sh
manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator.go
pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator_test.go
test/e2e/nodemaintenance_test.go
test/manifests/fake-etcd-quorum-guard.yaml

For the master quorum validation we check the PodDisruptionBudget of the etcd-quorum-guard. When it allows disruptions, we can
put a master node into maintenance.
This works on Openshift only, on k8s clusters (not having the etcd-quorum-guard) this validation will be skipped.
For e2e tests on k8s a fake PDB will be created.
Replaces #76 
```release-note
Added master quorum validation
```

Added master quorum validation

---

pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator.go
test/manifests/fake-etcd-quorum-guard.yaml

The etcd-quorum-guard moved from `openshift-machine-config-operator` to `openshift-etcd`
```release-note
NONE
```

Fixed namespace of etcd-quorum-guard PDB

---

hack/functest.sh
hack/sync-deploy.sh
test/e2e/nodemaintenance_test.go

Running the e2e test on OpenshiftCI revealed some issues:
- putting master nodes into maintenance at (nearly) the same time won't be prevented by the master quorum validation, because the etcd-quorum-guard PDB isn't updated fats enough.
- the lease was expected in the wrong namespace
- seems the webhook setup is slower, so wait a bit after NMO deployment (update to a better solution when https://github.com/kubernetes-sigs/controller-runtime/issues/723 is fixed)

Fix e2e test

---

cmd/manager/main.go
deploy/deployment-k8s/operatorgroup.yaml
deploy/deployment-ocp/operatorgroup.yaml
deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
deploy/operatorgroup.yaml
hack/sync-deploy.sh
manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v9.9.9/manifests/node-maintenance-operator.clusterserviceversion.yaml

Background: HCO is switching from deploying NMO itself to making NMO a dependency only. HCO uses the ownNamespace installMode, and because of that OLM tries to install NMO in ownNamespace mode as well, which isn't allowed so far and makes the deployment fail.
With this PR NMO allows ownNamespace installMode. But that also has an issue: webhooks are misconfigured by OLM, cluster scoped resources would not be handled. So a workaround for this is added as well.
```release-note
Allow ownNamespace installMode
```

Allow ownNamespace installMode

---

cmd/manager/main.go

The latter works better with evicted pods, and since NMO actively evicts
pods, there is some chance that it evicts itself as well.
See https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#leader-election
```release-note
Switch from leader-for-life to leader-with-lease
```

Switch from leader-for-life to leader-with-lease

---

Makefile
cmd/manager/main.go
version/version.go

Git version, commit hash and build date: 
```
$ ./_out/node-maintenance-operator
...
{"level":"info","ts":1598949801.267715,"logger":"cmd","msg":"Operator Version: v0.6.0-102-g3937d3d5"}
{"level":"info","ts":1598949801.2677214,"logger":"cmd","msg":"Git Commit: 3937d3d5cfa3558526782680766e5ce87a58f630"}
{"level":"info","ts":1598949801.2677276,"logger":"cmd","msg":"Build Date: 2020-09-01T08:43:15+00:00"}
...
```
```release-note
Added Git version, commit hash and build date to version info
```

Add some useful version info

---

test/e2e/e2e_suite_test.go
test/e2e/node_maintenance_test.go

Ignore errors like
- connect: connection refused
- no endpoints available for service "node-maintenance-operator-service"
They can be caused by webhooks not being ready yet or unavailable master nodes
```release-note
NONE
```

Retry CR creation in case of unexpected errors

---

Makefile
build/Dockerfile
build/bin/user_setup
build/hco/csv-generator
deploy/crds/nodemaintenance_cr.yaml
deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
go.sum
manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v9.9.9/manifests/node-maintenance-operator.clusterserviceversion.yaml

Since NMO continues to be delivered as part of HCO we needed to re-add the csv-generator script, also we don't need to support the allNamespaces installMode for this version
```release-note
NONE
```

Re-added csv-generator

---

build/index.Dockerfile.ci.intermediate

index image build fails on Openshift CI, seems it needs root user now...

Fix OpenshiftCI

---

.dockerignore
Makefile
build/check.Dockerfile
deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
deploy/operator.yaml
manifests/node-maintenance-operator/v0.8.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v9.9.9/manifests/node-maintenance-operator.clusterserviceversion.yaml

CNV uses the subscription to set a node selector, which conflicts with the node affinity.
```release-note
Removed master node affinity
```

Bug 1895033: Remove master node affinity

---

test/e2e/node_maintenance_test.go

increase test deployment grace period such that NMO controller will need to requeue after fixed duration to fix e2e tests
```release-note-none```

Fix e2e test failing on missing "Reconciling with fixed duration" log message

---

README.md
build/index.Dockerfile.ci.intermediate

Sonarcloud integration was added by the kubevirt team... let's see what happens
https://sonarcloud.io/project/configuration?id=kubevirt_node-maintenance-operator
/hold

README change for triggering Sonarcloud

---

Makefile
build/Dockerfile
manifests/node-maintenance-operator/v0.9.1/manifests/node-maintenance-operator.clusterserviceversion.yaml
manifests/node-maintenance-operator/v0.9.1/manifests/nodemaintenance.kubevirt.io_nodemaintenances_crd.yaml
manifests/node-maintenance-operator/v0.9.1/metadata/annotations.yaml
manifests/node-maintenance-operator/v0.9.1/node-maintenance-operator.package.yaml
pkg/controller/nodemaintenance/check_lease_update_test.go
pkg/controller/nodemaintenance/lease.go
test/e2e/node_maintenance_test.go

Use coordination API version v1, v1beta1 is deprecated
According to [1], there is no need for migration of existing lease
resources: "All existing persisted objects are accessible via the
new API"
Add version 0.9.1 manifests
[1] https://kubernetes.io/docs/reference/using-api/
```release-note
Update coordination API version to v1, v1beta1 is deprecated
```

Update coordination version

---

Makefile
api/v1beta1/nodemaintenance_webhook_test.go
automation/test.sh
build/Dockerfile
build/bundle.Dockerfile
build/readme.txt

- remove automation dir, was used by KubeVirtCI e2e, which we don't use anymore
- remove build dir, OpenshiftCI uses correct Dockerfile locations now
- remove outdated comment in Makefile
don't merge before
https://github.com/kubevirt/project-infra/pull/1650
https://github.com/openshift/release/pull/22504
/hold

Some cleanup after CI updates

---

bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml
config/manifests/bases/node-maintenance-operator.clusterserviceversion.yaml

Adding `'["disconnected"]'` label to `config/manifests/bases/node-maintenance-operator.clusterserviceversion.yaml` file, and then running  `make bundle` to support disconnected environment with NMO.
```release-note
Add annotation to support disconnected mode
```

Add annotation to support disconnected mode

---

Dockerfile

CentOS Stream 8 is now scheduled for EOL as stated in https://www.centos.org/centos-stream/.
Therefore this PR updates CentOS version in Dockerfile for new builds to use CentOS Stream 9, which is in full support phase.
**Release note**:
```release-note
Update Dockerfile to use CentOS Stream 9
```
Signed-off-by: João Vilaça <jvilaca@redhat.com>

Update Dockerfile to use centos:stream9

---

bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml
config/manager/manager.yaml
hack/csv-generator.sh

Since we don't have `kubevirt-cluster-critical` in CI, use `system-cluster-critical` and switch in the CSV generator for HCO.
Fixes bz2008960.

Add priorityClassName

---

README.md

```release-note
Adding reference to Medik8s NMO
```
Since NMO has been moved out of KubeVirt we add a reference to the active development version of NMO.

Adding reference to Medik8s NMO
